/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GraalDateParseTest;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;

public class AppTest {
    @Test public void testAppHasAGreeting() throws IOException {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.runWorking(1));
    }
}
